# Generated by Django 5.2.8 on 2025-12-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('service', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmé'), ('REJECTED', 'Refusé')], default='PENDING', max_length=50)),
            ],
        ),
    ]
