# Generated by Django 5.2.9 on 2025-12-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_rdv_client_account_alter_rdv_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
