# Generated by Django 5.2.9 on 2025-12-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
